version: '3'

services:
  db:
    image: mysql:5.7
    command: 
      --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    ports:
      - '3306:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=StoreManager
    volumes:
      - ../dataMysql:/var/lib/mysql
    